### ISSUE TITLE
Unhandled promise rejection.

### ISSUE THREAD

**Issue by ZacharyDuBois** [Ominousness/discord-purge#3]
When trying to delete a call history item (which is seems Discord no longer lets you), Promise throws a unhandled exception resulting in the following:

```
(node:1500) UnhandledPromiseRejectionWarning: StatusCodeError: 403 - "{\"code\": 50021, \"message\": \"Cannot execute action on a system message\"}"
    at new StatusCodeError (./discord-purge-master/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (./discord-purge-master/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (./discord-purge-master/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (./discord-purge-master/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (./discord-purge-master/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (./discord-purge-master/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
(node:1500) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1500) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Seems to happen when Discord returns a 403. Should probably add some exception handling there and just retry a few times or pass over the message.

**Comment by DaJakerBoss** [comment]
I too am stuck at this step. I'm trying to delete past this and I cannot seem to do so since each run catches this call message. Is there any workaround that you're aware of or is it pretty much stuck at this point, since I'm trying to delete everything and still have upwards of 1k to go

**Comment by Veklu** [comment]
Here is a dirty fix for it
line 62 await removeMessage(messages[i].channel_id, messages[i].id).catch(function(err) {});
